services:
  job.api:
    image: ${DOCKER_REGISTRY-}jobapi
    build:
      context: .
      dockerfile: Job.API/Dockerfile

  azure-cosmosdb-local:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: azure-cosmosdb-local
    
volumes:
    azure_cosmosdb_data:
        
