services:
  job.api:
    image: ${DOCKER_REGISTRY-}jobapi
    build:
      context: .
      dockerfile: Job.API/Dockerfile

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    
volumes:
    dynamodb_data:
        
